# This is a basic workflow to help you get started with Actions

name: Arduino Library CI

# Controls when the workflow will run
on:[pull_request, push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: arduino/arduino-lint-action
  # You may pin to the exact commit or the version.
  # uses: arduino/arduino-lint-action@e9a30879471dcbf7d9fe3481b26e60b652cca297
        uses: arduino/arduino-lint-action@v1.0.2
        with:
          # Path containing Arduino projects.
          path: # optional
          # Version of the Arduino Lint tool to use.
          version: # optional, default is 1.x
          # How strict the checks are.
          compliance: # optional, default is specification
          # Configuration of the checks for libraries in the Arduino Library Manager index.
          library-manager: # optional
          # The type of project to check.
          project-type: # optional, default is all
          # Search path recursively for projects to check.
          recursive: # optional, default is false
          # Save a JSON formatted report on the checks to this file.
          report-file: # optional
          # Show more information on the checks being run.
          verbose: # optional, default is false
          # Run the checks that only apply to official (non 3rd party) Arduino projects.
          official: # optional, default is false
          # GitHub access token used to get information from the GitHub API.
          token: # optional, default is ${{ github.token }}
